name: test caller workflow to be called

on:
  workflow_call:
    secrets:
      TEST_SECRET:
        description: test secret
        required: false

jobs:
  self:
    runs-on: ubuntu-latest
    env:
      test: $(secrets.TEST_SECRET)
    steps:
      - name: test secrets
        run: |
          echo $PATH
          export