name: test for secret passing

on:
    push:
        branches:
            - main

jobs:
    test:
        uses: rmdwe/test-runner/.github/workflows/test_caller.yaml@main
        secrets: 
            TEST_SECRET: ${{ secrets.TEST_SECRET_NONPROD }}
